export const contactFormStrings = {
  nameRequired: 'Please enter your name.',
  invalidEmail: 'Entered email is invalid',
  emailRequired: 'Please enter your email.',
  messageRequired: 'Please enter a message.',
  termsAcceptanceRequired: 'You need to accept Terms and Conditions.',
  nameLabel: '*Name:',
  namePlaceholder: 'Enter your name',
  emailLabel: '*Email:',
  emailPlaceholder: 'Enter your email',
  textAreaLabel: '*Message:',
  textAreaPlaceholder: 'Enter your message',
  termsLabel: 'Accept Terms and Conditions',
  sendMessageButtonLabel: 'Send message',
  alertMessage: 'Message sent!',
  myEmail: 'jan.jaroszczak@gmail.com',
  myPhoneNumberLink: '+48500170887',
  myPhoneNumberLabel: '+48 500 170 887',
  linkedInLink: 'https://www.linkedin.com/in/jan-jaroszczak/',
  gitHubLink: 'https://github.com/JanJaroszczak',
};
